main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('videogames/', views.videogames_index, name='index'),
  path('videogames/<int:videogame_id>/', views.videogames_detail, name='detail'),
  path('videogames/create/', views.VideoGameCreate.as_view(), name='videogames_create'),
  path('videogames/<int:pk>/update', views.VideoGameUpdate.as_view(), name='videogames_update'),
  path('videogames/<int:pk>/delete', views.VideoGameDelete.as_view(), name='videogames_delete'),
  path('videogames/<int:videogame_id>/add_stream/', views.add_stream, name='add_stream'),
  path('videogames/<int:videogame_id>/assoc_platform/<int:platform_id>/', views.assoc_platform, name='assoc_platform'),
  path('videogames/<int:videogame_id>/unassoc_platform/<int:platform_id>/', views.unassoc_platform, name='unassoc_platform'),
  path('platforms/', views.PlatformList.as_view(), name='platforms_index'),
  path('platforms/<int:pk>/', views.PlatformDetail.as_view(), name='platforms_detail'),
  path('platforms/create/', views.PlatformCreate.as_view(), name='platforms_create'),
  path('platforms/<int:pk>/update/', views.PlatformUpdate.as_view(), name='platforms_update'),
  path('platforms/<int:pk>/delete/', views.PlatformDelete.as_view(), name='platforms_delete'),
]

videogamecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Platform(models.Model):
  name = models.CharField(max_length=50)
  link = models.URLField(max_length=50)

  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('platforms_detail', kwargs={'pk': self.id})

class VideoGame(models.Model):
  title = models.CharField(max_length=100)
  genre = models.CharField(max_length=100)
  description = models.TextField(max_length=250)
  release_year = models.IntegerField()
  platforms = models.ManyToManyField(Platform)

  def __str__(self):
    return f'{self.title} ({self.id})'

  def get_absolute_url(self):
    return reverse('detail', kwargs={'videogame_id': self.id})
  
class Stream(models.Model):
  date = models.DateField('stream date')
  time = models.TimeField()
  # Create a videogame_id FK
  videogame = models.ForeignKey(VideoGame, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.time} on {self.date}"

  class Meta:
    ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Stream

class StreamForm(ModelForm):
  class Meta:
    model = Stream
    fields = ['date', 'time']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .models import VideoGame, Platform
from .forms import StreamForm

# Create your views here.
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def videogames_index(request):
    videogames = VideoGame.objects.all() # Retrieve all videogames
    return render(request, 'videogames/index.html', 
    { 
        'videogames': videogames 
    }
)

def videogames_detail(request, videogame_id):
  videogame = VideoGame.objects.get(id=videogame_id)
  id_list = videogame.platforms.all().values_list('id')
  platforms_videogame_doesnt_have = Platform.objects.exclude(id__in=id_list)
  stream_form = StreamForm()
  return render(request, 'videogames/detail.html', { 
    'videogame': videogame,
    'stream_form': stream_form,
    'platforms': platforms_videogame_doesnt_have
  })

def add_stream(request, videogame_id):
  # create a ModelForm instance using the data in request.POST
  form = StreamForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the videogame_id assigned
    new_stream = form.save(commit=False)
    new_stream.videogame_id = videogame_id
    new_stream.save()
  return redirect('detail', videogame_id=videogame_id)

class VideoGameCreate(CreateView):
   model = VideoGame
   fields = ['title', 'genre', 'description', 'release_year']

class VideoGameUpdate(UpdateView):
   model = VideoGame
   fields = ['genre', 'description', 'release_year']

class VideoGameDelete(DeleteView):
   model = VideoGame
   success_url = '/videogames'

class PlatformList(ListView):
  model = Platform

class PlatformDetail(DetailView):
  model = Platform

class PlatformCreate(CreateView):
  model = Platform
  fields = '__all__'

class PlatformUpdate(UpdateView):
  model = Platform
  fields = ['name', 'color']

class PlatformDelete(DeleteView):
  model = Platform
  success_url = '/platforms'

def assoc_platform(request, videogame_id, platform_id):
  VideoGame.objects.get(id=videogame_id).platforms.add(platform_id)
  return redirect('detail', videogame_id=videogame_id)

def unassoc_platform(request, videogame_id, platform_id):
  VideoGame.objects.get(id=videogame_id).platforms.remove(platform_id)
  return redirect('detail', videogame_id=videogame_id)

main_app/templates/about.html
{% extends 'base.html' %}

{% block content %}
<h1>About the Video Game Collector</h1>
<hr />
<p>Hire the Video Game Collector!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Video Game Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="{% url 'home' %}" class="left brand-logo">&nbsp;&nbsp;Video Game Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about' %}">About</a></li>
          <li><a href="{% url 'platforms_create' %}">Add a Platform</a></li>
          <li><a href="{% url 'platforms_index' %}">View All Platforms</a></li>
          <li><a href="{% url 'videogames_create' %}">Add a Video Game</a></li>
          <li><a href="{% url 'index' %}">View All My Video Games</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 Video Game Collector &nbsp;</div>
  </footer>
</body>

</html>

main_app/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Home</h1>
{% endblock %}

main_app/templates/main_app/platform_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Platform</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn">
  <a href="{% url 'platforms_detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/platform_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Platform Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ platform.name }}</span>
        <p>Link: {{ platform.link }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'platforms_update' platform.id %}">Edit</a>
        <a href="{% url 'platforms_delete' platform.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/platform_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Platform</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}

main_app/templates/main_app/platform_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Platform List</h1>

{% for platform in platform_list %}
<a href="{% url 'platforms_detail' platform.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ platform.name }}</span>
      <p>Link: {{ platform.link }}</p>
    </div>
  </div>
</a>
{% endfor %}

{% endblock %}

main_app/templates/main_app/videogame_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Video Game</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes - Delete!" class="btn">
  <a href="{% url 'detail' videogame.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/videogame_form.html
{% extends 'base.html' %}

{% block content %}

{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Video Game</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="POST">
  <!-- Django requires the following for security purposes -->
  {% csrf_token %}
  <table>
    <!-- Render the inputs inside of <tr>s & <td>s -->
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit!" class="btn">
</form>

{% endblock %}

main_app/templates/videogames/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Video Game Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ videogame.title }}</span>
        <p>Genre: {{ videogame.genre }}</p>
        <p>Description: {{ videogame.description|linebreaks }}</p>
        {% if videogame.release_year > 0 %}
        <p>Release Year: {{ videogame.release_year }}</p>
        {% else %}
        <p>Release Year: Pre-historic</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'videogames_update' videogame.id %}">Edit</a>
        <a href="{% url 'videogames_delete' videogame.id %}">Delete</a>
      </div>
    </div>
  </div>
  <div class="col s6">
    <form action="{% url 'add_stream' videogame.id %}" method="POST">
      {% csrf_token %}
      <!-- Render the inputs -->
      {{ stream_form.as_p }}
      <input type="submit" class="btn" value="Add Stream">
    </form>
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Time</th>
        </tr>
      </thead>
      <tbody>
        {% for stream in videogame.stream_set.all %}
        <tr>
          <td>{{stream.date}}</td>
          <td>{{stream.time}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr>
<div class="row">
  <div class="col s6">
    <h3>Streaming Platforms</h3>
    {% if videogame.platforms.count %}
    {% for platform in videogame.platforms.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title">
          {{ platform.name }} at {{ platform.link }}
        </span>
      </div>
      <div class="card-action">
        <form action="{% url 'unassoc_platform' videogame.id platform.id %}" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn">Remove</button>
        </form>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <h5>No Streaming Platforms 😪</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Platforms</h3>
    {% if platforms.count %}
      {% for platform in platforms.all %}
      <div class="card">
        <div class="card-content">
          <span class="card-title">
            {{ platform.name }} at {{ platform.link }}
          </span>
        </div>
        <div class="card-action">
          <form action="{% url 'assoc_platform' videogame.id platform.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn">Add</button>
          </form>
        </div>
      </div>
      {% endfor %}
    {% else %}
    <h5>{{videogame.name}} Already Has All Platforms Available</h5>
    {% endif %}
  </div>
</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });

  // add additional JS to initialize select below
  const timeEl = document.getElementById('id_time');

  M.Timepicker.init(timeEl, {
    autoClose: true,
    twelveHour: false
  });
</script>
{% endblock %}

main_app/templates/videogames/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Video Game List</h1>

{% for videogame in videogames %}
<div class="card">
  <a href="{% url 'detail' videogame.id %}">
    <div class="card-content">
      <span class="card-title">{{ videogame.title }}</span>
      <p>Genre: {{ videogame.genre }}</p>
      <p>Description: {{ videogame.description|linebreaks }}</p>
      {% if videogame.release_year > 0 %}
      <p>Release Year: {{ videogame.release_year }}</p>
      {% else %}
      <p>Release Year: Pre-historic</p>
      {% endif %}
    </div>
  </a>
</div>
{% endfor %}

{% endblock %}